#!/usr/bin/env bash
# Stamp a <base href> into every HTML page so bare-relative references resolve
# correctly no matter where the site is mounted.
#
# Why this exists
# ---------------
# GitHub Pages redirects /arcade  -> /arcade/   (adds a trailing slash)
# Webflow Cloud    redirects /arcade/ -> /arcade   (strips it)
#
# Under the strip convention the browser treats the last path segment as a
# FILE, so a bare href="app.js" on /arcade resolves to /app.js instead of
# /arcade/app.js. A <base> tag pins the directory explicitly and fixes every
# relative href, src, CSS url() and fetch() in one line per page.
#
# Usage
#   tools/set-base.sh /d13-app    # mounted at nycfirst.org/d13-app
#   tools/set-base.sh /           # mounted at a domain/subdomain root
#
# To verify rather than change, re-run and let git answer — the script is
# idempotent, so a clean diff means every stamp is already correct:
#   tools/set-base.sh /d13-app && git diff --exit-code -- '*.html'
#
# Idempotent: re-running replaces the existing tag rather than adding another.

set -euo pipefail
cd "$(dirname "$0")/.."

MOUNT="${1:-}"
if [ -z "$MOUNT" ] || [ "${MOUNT#-}" != "$MOUNT" ]; then
  # A leading dash is a flag, not a mount path. Without this guard a stray
  # --check would be stamped verbatim as <base href="/--check/">.
  echo "usage: tools/set-base.sh <mount-path>   e.g. /d13-app  or  /" >&2
  exit 2
fi

# Normalise: leading slash, no trailing slash. "/" becomes "".
[ "${MOUNT#/}" = "$MOUNT" ] && MOUNT="/$MOUNT"
MOUNT="${MOUNT%/}"

changed=0
skipped=0

while IFS= read -r f; do
  # A page needs a <head> to hold the tag. Fragments (no <head>) are skipped;
  # they are included by a parent document and inherit its base.
  if ! grep -qi '<head>' "$f"; then
    printf '  skip   %-36s (no <head>)\n' "$f"
    skipped=$((skipped + 1))
    continue
  fi

  dir="$(dirname "$f")"
  stem="$(basename "$f" .html)"

  # Every page's base is simply the directory it lives in. An app page sits
  # inside its own app directory (arcade/arcade.html), so its assets resolve
  # from there; the short URL /arcade is wired up by _redirects below.
  if [ "$dir" = "." ]; then
    base="$MOUNT/"
  else
    base="$MOUNT/$dir/"
  fi

  tag="<base href=\"$base\">"

  # Drop any previous stamp, then insert directly after <head>.
  perl -0pi -e 's{\n[ \t]*<base [^>]*>(?:[ \t]*<!-- set-base\.sh -->)?}{}g' "$f"
  perl -0pi -e "s{(<head>)}{\$1\n  $tag <!-- set-base.sh -->}i" "$f"

  printf '  base   %-36s %s\n' "$f" "$base"
  changed=$((changed + 1))
done < <(git ls-files '*.html')

echo
echo "stamped $changed file(s), skipped $skipped."

# ---------------------------------------------------------------------------
# _redirects - short URLs for the app pages
#
# An app page lives inside its own directory (arcade/arcade.html), which serves
# at /arcade/arcade. A 200 proxy rule makes /arcade serve that same page with
# no redirect at all, so the short URL is what users see and type.
#
# Two rules learned the hard way against the live site (see Webflow-plan.md):
#   - Both the source AND the target carry the mount path. A bare source never
#     matches under a mount.
#   - The target must be an extensionless URL. A target ending in .html picks
#     up the worker's extension-strip 307 afterwards, and for index.html that
#     lands on the trailing-slash form and loops. Hence no index.html anywhere.
# ---------------------------------------------------------------------------
{
  echo "# Generated by tools/set-base.sh - do not edit by hand."
  echo "# Short URLs for app pages: serve <app>/<app>.html at <app>, no redirect."
  echo
  # The app root itself. Written without a trailing slash: the Webflow site
  # edge 301s /x/ to /x before the worker ever sees the rule.
  echo "${MOUNT:-/}   $MOUNT/home   200"
  for page in $(git ls-files '*/*.html'); do
    d="$(dirname "$page")"
    [ "$d/$(basename "$d").html" = "$page" ] || continue
    printf '%s   %s   200\n' "$MOUNT/$d" "$MOUNT/$d/$(basename "$d")"
  done
} > _redirects

rules=$(grep -c '200$' _redirects)
echo "wrote _redirects with $rules short-URL rule(s)."
